/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dairysmart;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Zack
 */
public class BirthDeathRateCalf extends javax.swing.JFrame {

    /**
     * Creates new form BirthDeathRateCalf
     */
    Connection con;
    ResultSet rs = null;
      PreparedStatement pst= null;
    /** Creates new form OwnerAttendenceSheet */
    public BirthDeathRateCalf() throws SQLException {
        initComponents();
        con=(Connection) SqlCon.ConnectDb();
        
        Update_table();
    }
    
    
    public void labe(String bb, String vb){
    
    ll.setText(bb);
    li.setText(vb);
    }
    
      public void close(){
    
    WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
private void Update_table() throws SQLException{
    
    String sql="select * from BirthDeathRateCalf";
    pst=(PreparedStatement) con.prepareStatement(sql);
    rs=pst.executeQuery();
    tab.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bir = new javax.swing.JTextField();
        det = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Date = new javax.swing.JCheckBox();
        txtt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ll = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        li = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calf Death And Birth Rate");
        setMinimumSize(new java.awt.Dimension(1300, 765));
        setPreferredSize(new java.awt.Dimension(1300, 750));
        getContentPane().setLayout(null);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(73, 65, 870, 440);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       CALF BIRTH AND DEATH RATE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(245, 11, 413, 36);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(959, 136, 45, 29);
        getContentPane().add(date1);
        date1.setBounds(1008, 134, 132, 33);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Birth:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(959, 186, 43, 32);
        getContentPane().add(bir);
        bir.setBounds(1012, 185, 128, 34);
        getContentPane().add(det);
        det.setBounds(1012, 237, 128, 35);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Death:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(955, 238, 47, 32);

        jButton2.setText("sumbit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1012, 298, 85, 30);
        getContentPane().add(txt);
        txt.setBounds(320, 520, 99, 31);

        jButton1.setText("Show In Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 520, 208, 30);

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(1146, 134, 21, 21);
        getContentPane().add(txtt);
        txtt.setBounds(630, 520, 75, 31);

        jButton3.setText("Total Birth");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 520, 90, 30);

        jButton4.setText("Total Death");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 520, 100, 30);

        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1190, 0, 70, 23);

        ll.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ll);
        ll.setBounds(1130, 0, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Insert Info");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1017, 99, 108, 29);

        li.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(li);
        li.setBounds(1070, 0, 50, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zack\\Documents\\NetBeansProjects\\DairySmart\\zack.jpg")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(1300, 765));
        jLabel6.setMinimumSize(new java.awt.Dimension(1300, 765));
        jLabel6.setPreferredSize(new java.awt.Dimension(1300, 765));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1310, 750);

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Owner Main Page");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Refresh");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Back");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Get Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

   try{
        
       String sql="Insert into BirthDeathRateCalf(Date,Birth,Death) values(?,?,?)"; 
      
            
         pst=(PreparedStatement) con.prepareStatement(sql);
 
         pst.setString(1, date1.getText());
         pst.setString(2, bir.getText());
          pst.setString(3, det.getText());
    
        
  
         pst.execute();
    
    
    }catch(Exception e){
        System.out.println(e);
    }
        try {
            Update_table();
           
        } catch (SQLException ex) {
            Logger.getLogger(WorkersSalarySheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        date1.setText("");
     
          bir.setText("");
           det.setText("");
           
             if(Date.isSelected()){
            Date.setSelected(false);
}
           
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         try{
        String sql="Select sum(Birth) from BirthDeathRateCalf";
        
         pst=(PreparedStatement) con.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next()){
         
         String sum=rs.getString("sum(Birth)");

         
         txt.setText(sum);
         }
        
        }catch(Exception e){
        
        }
         
          try{
        String sql="Select sum(Death) from BirthDeathRateCalf";
        
         pst=(PreparedStatement) con.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next()){
         
         String sum=rs.getString("sum(Death)");

         
         txtt.setText(sum);
         }
        
        }catch(Exception e){
        
        }
        
        
        
       String g=txt.getText();
       String gg=txtt.getText();
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
     
     
     
     dataset.setValue(new Double(g), "Values", "Birth Rate");
 dataset.setValue(new Double(gg), "Values", "Death Rate");
//  dataset.setValue(5, "Science", "Deepak");
//  dataset.setValue(3, "Maths", "Deepak");
//  dataset.setValue(6, "Science", "Vinod");
//  dataset.setValue(9, "Maths", "Vinod");
//  dataset.setValue(2, "Science", "Chandan");
//  dataset.setValue(4, "Maths", "Chandan");
 JFreeChart chart = ChartFactory.createBarChart3D
  ("show chart","Growth", "", dataset, PlotOrientation.VERTICAL, true,true, false);
  chart.setBackgroundPaint(Color.yellow);
  chart.getTitle().setPaint(Color.blue); 
  CategoryPlot p = chart.getCategoryPlot(); 
  p.setRangeGridlinePaint(Color.red); 
  ChartFrame frame1=new ChartFrame("3D Bar Chart",chart);
  frame1.setVisible(true);
  frame1.setSize(900,600);
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          try{
        String sql="Select sum(Birth) from BirthDeathRateCalf";
        
         pst=(PreparedStatement) con.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next()){
         
         String sum=rs.getString("sum(Birth)");

         
         txt.setText(sum);
         }
        
        }catch(Exception e){
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

          try{
        String sql="Select sum(Death) from BirthDeathRateCalf";
        
         pst=(PreparedStatement) con.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next()){
         
         String sum=rs.getString("sum(Death)");

         
         txtt.setText(sum);
         }
        
        }catch(Exception e){
        
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed

         Calendar cal= new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
     int year=cal.get(Calendar.YEAR);
      int day=cal.get(Calendar.DAY_OF_MONTH);
      date1.setText(year+"/"+(month+1)+"/"+day);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
           try {
              close();
              MainFrame a= new MainFrame();
              a.setVisible(true);
              
              
              // TODO add your handling code here:
          } catch (Exception ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        
        
        // TODO add your handling code here:
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

           try {
              
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Zack\\Documents\\NetBeansProjects\\DairySmart\\Help.pdf");
              
              // TODO add your handling code here:
          } catch (Exception ex) {
             
        
        
     
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        
        txt.setText("");
         txtt.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

          String bg=li.getText();
           String ws=ll.getText();
        
              try {
              close();
              WorkersAttendenceSheet a= new WorkersAttendenceSheet();
              a.setVisible(true);
              a.labe(ws,bg);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(Level.SEVERE, null, ex);
          
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        String bg=li.getText();   
        String ds=ll.getText();
        
        if(ds.equalsIgnoreCase("Worker")){
        
         JOptionPane.showMessageDialog(null, "You are not Allow to access the page");
        }
        if(ds.equalsIgnoreCase("Owner")){
       
            try{
                close();
        OwnerAttendenceSheet nn= new OwnerAttendenceSheet();
        nn.labe(ds,bg);
        nn.setVisible(true);
            }catch(Exception ex){


}
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirthDeathRateCalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirthDeathRateCalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirthDeathRateCalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirthDeathRateCalf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BirthDeathRateCalf().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BirthDeathRateCalf.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Date;
    private javax.swing.JTextField bir;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField det;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel li;
    private javax.swing.JLabel ll;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtt;
    // End of variables declaration//GEN-END:variables
}
