/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WorkersAttendenceSheet.java
 *
 * Created on Apr 19, 2013, 8:51:48 AM
 */
package dairysmart;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zack
 */
public class WorkersAttendenceSheet extends javax.swing.JFrame {
 Connection connn;
  String we="";
 String  prp="";
 
   String prpn="";
   Connection con;
    Connection conn;
    ResultSet rs = null;
       ResultSet rss = null;
      ResultSet rst = null;
      PreparedStatement pst= null;
     PreparedStatement pstt= null;
    PreparedStatement pstn= null;
    /** Creates new form WorkersAttendenceSheet */
    public WorkersAttendenceSheet() throws SQLException {
        initComponents();
       con=(Connection) SqlCon.ConnectDb();
        
        Update_table();
    }
   
    
    
    public void labe(String bb, String re){
    
    ll.setText(bb);
    li.setText(re);
    }

    private void Update_table() throws SQLException{
    
    String sql="select Serial as'Serial',Date as'Date',Name as'Name', StartTime as'Start Time', EndTime as'End Time', WorkingHour as'Working Hour', Status as'Status' from WorkersAttendenceSheet";
    pst=(PreparedStatement) con.prepareStatement(sql);
    rs=pst.executeQuery();
    Table_Worker.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
     public void close(){
    
    WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Worker = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        worker = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ll = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        li = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome to workers attendence sheet");
        setMinimumSize(new java.awt.Dimension(1280, 765));
        getContentPane().setLayout(null);

        Table_Worker.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Table_Worker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Worker.setEnabled(false);
        jScrollPane1.setViewportView(Table_Worker);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(413, 83, 769, 452);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Show Workers Attecdence Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 40, 369, 28);

        worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerActionPerformed(evt);
            }
        });
        getContentPane().add(worker);
        worker.setBounds(90, 320, 259, 40);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 170, 250, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("        Serial:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 330, 60, 22);

        jButton2.setText("End");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 370, 97, 30);

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1180, 0, 80, 23);

        ll.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ll);
        ll.setBounds(1140, 0, 40, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Insert Attendence Information");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 100, 220, 30);

        li.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(li);
        li.setBounds(1080, 0, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign Out Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 280, 170, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zack\\Documents\\NetBeansProjects\\DairySmart\\zack.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1310, 750);

        jMenu1.setText("File");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Loss and Profit Sheet");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Owner Main Page");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Daily Milk Sell");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Cows Milk Save Amount");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Cows Health Care ");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Cow Registration");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Cows Food Option");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Calf Registration");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Death And Brith Rate Of Calf");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Simple Calculator");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Get Help");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void workerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerActionPerformed

    
    
    
   
}//GEN-LAST:event_workerActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

   String sw=li.getText();
        
    String value1=worker.getText();
       Calendar cal= new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
     int year=cal.get(Calendar.YEAR);
      int day=cal.get(Calendar.DAY_OF_MONTH);
     String gg=(year+"/"+(month+1)+"/"+day);
  
   

try{

 String sql="Select Date,Name from workersattendencesheet where Serial='"+value1+"'";

    pst=(PreparedStatement) con.prepareStatement(sql);
 

  

          rs=pst.executeQuery();
       
         if(rs.next()){
         
              we=rs.getString("Name");
     
       
        prpn=rs.getString("Date");
        
         
       }
 
         System.out.println(prpn);
         System.out.println(we);
}catch(Exception e){}
     
     
     
  if(sw.equalsIgnoreCase(we)&& prpn.equalsIgnoreCase(gg)){
    
      System.out.println("thiss");
    
     
  try{  
     
      String sql="Select StartTime from workersattendencesheet where Serial='"+value1+"'";
           
      
            
         pst=(PreparedStatement) con.prepareStatement(sql);
 

  

          rs=pst.executeQuery();
       
         if(rs.next()){
         
         //    String add=rs.getString("Date");
     
       
        prp=rs.getString("StartTime");
      
         
       }
      
     
          System.out.println(prp); 
         
         
  }catch(Exception e){
      System.out.println(e);
  
  }
     
     
     
     
     
     
       SimpleDateFormat sdfDate = new SimpleDateFormat("HH:mm:ss");//dd/MM/yyyy
    Date now = new Date();
    String s = sdfDate.format(now);
       
    SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
    
    
                Date d1 = null;
		Date d2 = null;
        try {
            d1 = format.parse(prp);
        } catch (ParseException ex) {
            Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            d2 = format.parse(s);
        } catch (ParseException ex) {
            Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(Level.SEVERE, null, ex);
        }
 
			//in milliseconds
			long diff = d2.getTime() - d1.getTime();
 
			long diffSeconds = diff / 1000 % 60;
			long diffMinutes = diff / (60 * 1000) % 60;
			long diffHours = diff / (60 * 60 * 1000) % 24;
    
                    String drsk=(diffHours+":"+diffMinutes+":"+diffSeconds);
    
    
    
      try{
    
   String sql="UPDATE WorkersAttendenceSheet SET EndTime='"+s+"',WorkingHour='"+drsk+"'  WHERE  Serial='"+value1+"'";
      
      String sqll="UPDATE WorkersAttendenceSheetZ SET EndTime='"+s+"',WorkingHour='"+drsk+"'  WHERE  Serial='"+value1+"'";        
   
 
      
         
      
               
      
      
      
      
     pst=(PreparedStatement) con.prepareStatement(sql);
 
//        
//  
       pst.execute();
//    
//    
          pstt=(PreparedStatement) con.prepareStatement(sqll);
 
        
  
       pstt.execute();
       
       
    }catch(Exception e){
        System.out.println(e);
    }
     
     
  
     
     
        try {
            Update_table();
           
           // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(WorkersSalarySheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              worker.setText("");
  }else{
   worker.setText("");
  JOptionPane.showMessageDialog(null,"You are not allowed to edit others time");
  
  
  }
       
      


    // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          String fd=li.getText();
      Calendar cal= new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
     int year=cal.get(Calendar.YEAR);
      int day=cal.get(Calendar.DAY_OF_MONTH);
      String ss=(year+"/"+(month+1)+"/"+day);
    
      SimpleDateFormat sdfDate = new SimpleDateFormat("HH:mm:ss");//dd/MM/yyyy
    Date now = new Date();
    String s = sdfDate.format(now);
        // starttime.setText(s);
     try{
        
       String sql="Insert into WorkersAttendenceSheet(Date, Name, StartTime) values(?,?,?)"; 
        String sqll="Insert into WorkersAttendenceSheetZ( Date, Name, StartTime) values(?,?,?)"; 
            
         pst=(PreparedStatement) con.prepareStatement(sql);
         
         
//         pst.setString(1, id.getText());
         pst.setString(1, ss);
         pst.setString(2, fd);
         pst.setString(3, s);
        
        
  
         pst.execute();
    
         
             pstt=(PreparedStatement) con.prepareStatement(sqll);
 
        // pstt.setString(1, id.getText());
         pstt.setString(1, ss);
          pstt.setString(2, fd);
         pstt.setString(3, s);
         
           pstt.execute();
    
    }catch(Exception e){
        System.out.println(e);
    }
        try {
            Update_table();
           
           // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(WorkersSalarySheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
          
          
            //salary.setText("");
 
      
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
               
       
         String qge=li.getText();
        String hh=ll.getText();
          try {
             
              close();
              DailySellingMilkSheet a= new DailySellingMilkSheet();
              a.setVisible(true);
              a.labe(hh,qge);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(DailySellingMilkSheet.class.getName()).log(Level.SEVERE, null, ex);
          
    }       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
              close();
              MainFrame a= new MainFrame();
              a.setVisible(true);
              
              
            
          } catch (Exception ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        
        
        
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        String qge=li.getText();
        String sap=ll.getText();
        try {
              close();
              CowsMilkGivingAmount a= new CowsMilkGivingAmount();
              a.setVisible(true);
              a.labe(sap,qge);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(CowsMilkGivingAmount.class.getName()).log(Level.SEVERE, null, ex);
          
    }    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
          
        String bg=li.getText();
        String ws=ll.getText();
           try {
              close();
              CowsHealthcareSheet sa= new CowsHealthcareSheet();
              sa.setVisible(true);
              sa.labe(ws,bg);
              
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(CowsHealthcareSheet.class.getName()).log(Level.SEVERE, null, ex);
          
    } 


// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        String bg=li.getText();
        String ws=ll.getText();
             try {
              close();
              CowRegistration sas= new CowRegistration();
              sas.setVisible(true);
              sas.labe(ws,bg);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(CowRegistration.class.getName()).log(Level.SEVERE, null, ex);
          
    } 
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        String bg=li.getText();
        String ws=ll.getText();
        
                try {
              close();
             CowFoodOption sass= new CowFoodOption();
              sass.setVisible(true);
              sass.labe(ws,bg);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(CowFoodOption.class.getName()).log(Level.SEVERE, null, ex);
          
    } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        String bg=li.getText();
        String ws=ll.getText();
        
                  try {
              close();
             CalfResgistration sss= new CalfResgistration();
              sss.setVisible(true);
              sss.labe(ws,bg);
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(CalfResgistration.class.getName()).log(Level.SEVERE, null, ex);
          
    }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

                String ff=ll.getText();
                String bg=li.getText();
                    try {
              close();
             BirthDeathRateCalf ss= new BirthDeathRateCalf();
              
             ss.labe(ff, bg);
             ss.setVisible(true);
              
              
              // TODO add your handling code here:
          } catch (SQLException ex) {
              Logger.getLogger(BirthDeathRateCalf.class.getName()).log(Level.SEVERE, null, ex);
          
    }
       
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

//         close();
        SimpleCalculator as= new SimpleCalculator();
        as.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

           try {
              
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Zack\\Documents\\NetBeansProjects\\DairySmart\\Help.pdf");
              
              // TODO add your handling code here:
          } catch (Exception ex) {
             
        
        
     
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

       String ds=ll.getText();
        
        if(ds.equalsIgnoreCase("Worker")){
        
         JOptionPane.showMessageDialog(null, "You are not Allow to access the page");
        }
        if(ds.equalsIgnoreCase("Owner")){
       
            try{
                close();
        LossProfitSheet nn= new LossProfitSheet();
        
        nn.setVisible(true);
            }catch(Exception ex){


}
        } // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

                
         String qge=li.getText();
        String ds=ll.getText();
        
        if(ds.equalsIgnoreCase("Worker")){
        
         JOptionPane.showMessageDialog(null, "You are not Allow to access the page");
        }
        if(ds.equalsIgnoreCase("Owner")){
       
            try{
                close();
        OwnerAttendenceSheet nn= new OwnerAttendenceSheet();
        nn.labe(ds,qge);
        nn.setVisible(true);
            }catch(Exception ex){

            }
}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new WorkersAttendenceSheet().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(WorkersAttendenceSheet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Worker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel li;
    private javax.swing.JLabel ll;
    private javax.swing.JTextField worker;
    // End of variables declaration//GEN-END:variables
}
